version: "3.8"
services:
  db:
    image: postgres
    container_name: qs_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=quiz_service_db
    ports:
      - "5432:5432"
    volumes:
      - /quiz-server-db-data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready"] # -d ${POSTGRES_DB} -U ${POSTGRES_USER}
    #   interval: 30s
    #   timeout: 60s
    #   retries: 5
    #   start_period: 80s  
  goose:
    build: 
      context: .
      dockerfile: goose.dockerfile
    container_name: qs_goose
    depends_on:
      - db
    # command: ["wait4x", "postgresql", "postgres://postgres:postgres@0.0.0.0:5432/quiz_service_db?sslmode=disable", "--", "./migrations/goose_script.sh"]
  qserver:
    build:
      context: .
      dockerfile: server.dockerfile
    container_name: qs_server
    ports:
      - "8080:8080"
      - "8081:8081"
    # restart: always
    depends_on:
      - db
      - goose
