socket:
  host: "localhost"
  grpcPort: "8080"
  httpPort: "8081"
quizApiKey: "cCP7GHWCoe2d4VBysvmaAT1x1hToB54mm1rdEiYK"
dsn: "host=localhost port=5432 user=postgres password=postgres dbname=quiz_service_db sslmode=disable"