socket:
  host: "localhost"
  grpc_port: "8080"
  http_port: "8081"
quiz_api_key: "cCP7GHWCoe2d4VBysvmaAT1x1hToB54mm1rdEiYK"
postgres: 
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "quiz_service_db"
  sslmode: "disable"